{include file="header.phtml"}
<form action="" method="post">
  <div>
    用户名
    <input type="text" name="username">
  </div>
  <div>
    密码
    <input type="text" name="password">
  </div>
  <div>
    昵称
    <input type="text" name="nickname">
  </div>
  <div>
    性别
    <input type="text" name="sex">
  </div>
  <div>
    年龄
    <input type="text" name="age">
  </div>
  <div>
    <button type="submit">注册</button>
  </div>
</form>
{include file="footer.phtml"}
