{include file="header.phtml"}
<a href="main.php?op=add">新增</a>
<a href="main.php?op=logout">登出</a>
<table>
  <tr>
    <th>ID</th>
    <th>用户名</th>
    <th>密码</th>
    <th>昵称</th>
    <th>年龄</th>
    <th>性别</th>
    <th>选项</th>
  </tr>
{foreach $list as $row}
  <tr>
    <td>{$row.id}</td>
    <td>{$row.username}</td>
    <td>{$row.password}</td>
    <td>{$row.nickname}</td>
    <td>{$row.age}</td>
    <td>{$row.sex}</td>
    <td>
      <a href="main.php?op=edit&id={$row.id}">编辑</a>
      <a href="main.php?op=del&id={$row.id}">删除</a>
    </td>
  </tr>
{/foreach}
</table>
{include file="footer.phtml"}
